name: SnoopCompile

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - uses: actions/checkout@v1
      - name: Generating precompile files
        run: julia --project=deps/SnoopCompile -e "include("snoopCompile.jl")"

      # https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: Update precompile_*.jl file
          PULL_REQUEST_TITLE: '[AUTO] Update precompile_*.jl file'
          PULL_REQUEST_LABELS: no changelog
          PULL_REQUEST_BRANCH: create-pull-request/pkg-update
          BRANCH_SUFFIX: none
      - name: Check output environment variable
        run: echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
